services:
  vergo_front:  # Define the service name
    container_name: vergo_front  # Name of the container
    build:
      dockerfile: Dockerfile  # Path to the Dockerfile used for building the image
    ports:
      - "8086:80"  # Map port 80 in the container to port 8086 on the host
    restart: always  # Automatically restart the container if it stops