# docker-compose.prod.yml
services:
  vergo_front:
    container_name: vergo_front
    image: vergo_front
    restart: always
    networks:
      - interservices

networks:
  interservices:
    external: true