export enum CODES {
  FAIL = 'FAIL',
  SUCCESS = 'SUCCESS',
  CREATE_PASSKEY_FAIL = 'CREATE_PASSKEY_FAIL',
  DELETE_PASSKEY_FAIL = 'DELETE_PASSKEY_FAIL',
  UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL',
  GET_PASSKEY_FOR_USER_FAIL = 'GET_PASSKEY_FOR_USER_FAIL',
  AUTH_FAIL_WRONG_CREDENTIAL = 'AUTH_FAIL_WRONG_CREDENTIAL',
}